### ISSUE TITLE
Build validation error with NSRDB on docker

### ISSUE THREAD

**Issue by aivanova5** [arras-energy/gridlabd-old#1098]
## Problem description
~~~
root@d31490a36236:/gridlabd/gldcore/geodata/autotest/test_datasets# cat gridlabd.err
*** geodata_weather.py unittest ***
ERROR [nsrdb_weather]: unable to get data (unable to get API key for NSRDB data - see `gridlabd nsrdb_weather help` for detail on NSRDB access credentials)
======================================================================
ERROR: test_weather (__main__.TestWeather)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 225, in getkeys
    with open(credential_file,"r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.nsrdb/credentials.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 247, in getyears
    data = getyear(year,lat,lon)
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 313, in getyear
    api = getkey()
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 236, in getkey
    email = getemail()
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 193, in getemail
    keys = getkeys().keys()
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 230, in getkeys
    raise Exception("unable to get API key for NSRDB data - see `gridlabd nsrdb_weather help` for detail on NSRDB access credentials")
Exception: unable to get API key for NSRDB data - see `gridlabd nsrdb_weather help` for detail on NSRDB access credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gridlabd/gldcore/geodata/autotest/test_datasets/../../geodata_weather.py", line 139, in test_weather
    result = apply(test,options=dict(geohash_resolution=6,key_index="name",starttime=starttime,stoptime=stoptime))
  File "/gridlabd/gldcore/geodata/autotest/test_datasets/../../geodata_weather.py", line 119, in apply
    weather = nsrdb_weather.getyears(years,lat,lon)
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 276, in getyears
    error(f"unable to get data ({err})",2)
  File "/usr/local/opt/gridlabd/4.2.30-220124-develop_fix_debian11_setup/share/gridlabd/nsrdb_weather.py", line 168, in error
    exit(code)
  File "/usr/local/lib/python3.9/_sitebuiltins.py", line 26, in __call__
    raise SystemExit(code)
SystemExit: 2

----------------------------------------------------------------------
Ran 1 test in 0.004s

FAILED (errors=1)
ERROR    [INIT] : GldMain::subcommand(format='%s',...): command '../unittest.sh' returns code 1
test_datasets.glm(7): #exec ../unittest.sh -- system('../unittest.sh') failed with status 1
FATAL    [INIT] : shutdown after command line rejected
~~~

## Steps to reproduce

(Explain how to reproduce the behavior, e.g.,)
`docker pull debian:11`
`docker run debian:11`
`apt install git`
`git clone https://github.com/slacgismo/gridlabd.git && cd gridlabd`
`./install.sh -v`

## Expected behavior

100% validation pass

## System information

* GridLAB-D version: HiPAS GridLAB-D 4.2.30-220214 (develop_fix_debian11_setup) Linux
* Operating system: Debian 11 on docker

**Comment by dchassin** [comment]
This is due to credentials required by NSRDB.  This is now blocked on GitHub actions runs.
