### ISSUE TITLE
Add support for python pdb

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#716]
## Background

Importing `module pdb` in python modules causes errors.

## Proposed solution

Enable redirection of input by making gridlabd a tty.

## Alternatives

None

## Additional context

None

**Comment by dchassin** [comment]
Pdb appears to work find now.  Create the following file:

test.glm:
~~~
#begin python 
import pdb
breakpoint()
#end
~~~

Then run
~~~
$ gridlabd test.glm
--Return--
> <string>(3)<module>()->None
(Pdb) help
Documented commands (type help <topic>):
========================================
EOF    c          d        h         list      q        rv       undisplay
a      cl         debug    help      ll        quit     s        unt      
alias  clear      disable  ignore    longlist  r        source   until    
args   commands   display  interact  n         restart  step     up       
b      condition  down     j         next      return   tbreak   w        
break  cont       enable   jump      p         retval   u        whatis   
bt     continue   exit     l         pp        run      unalias  where    

Miscellaneous help topics:
==========================
exec  pdb

(Pdb) quit
ERROR    [INIT] : python_parser(NULL,...): command 'from gridlabd import *
import pdb
breakpoint()
' failed
ERROR    [INIT] : traceback of command 'from gridlabd im...'...
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/bdb.py", line 92, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/bdb.py", line 154, in dispatch_return
    if self.quitting: raise BdbQuit
bdb.BdbQuit
~~~
