### ISSUE TITLE
Docker develop image fails autotest

### ISSUE THREAD

**Issue by dchassin** [arras-energy/gridlabd-old#742]
## Problem description

During the autotest for `gldcore/autotest/test_require_pwlf.glm` on Docker image `slacgismo/gridlabd:develop` the following output is generated:

~~~
WARNING: Skipping pwlf as it is not installed.
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7m1e85sc/pwlf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7m1e85sc/pwlf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-7m1e85sc/pwlf/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 20, in <module>
        from setuptools.dist import Distribution, Feature
      File "/usr/local/lib/python3.7/site-packages/setuptools/dist.py", line 35, in <module>
        from setuptools import windows_support
      File "/usr/local/lib/python3.7/site-packages/setuptools/windows_support.py", line 2, in <module>
        import ctypes
      File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ModuleNotFoundError: No module named '_ctypes'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
ERROR    [INIT] : GldMain::subcommand(format='%s/gridlabd-%s',...): command '/usr/local/opt/gridlabd/4.2.1-200807-master/bin/gridlabd-require pwlf
' returns code 1
~~~

## Expected behavior

At worst, only this should be displayed the first time it runs on a system. (Maybe a pip update warning is displayed too).

~~~
WARNING: Skipping pwlf as it is not installed.
~~~

## Proposed solution

Update the docker base image to fix Python 3.7.7:

~~~
host# cd /usr/local/src/Python-3.7.7
host# yum install libffi-devel
host# ./configure --enable-optimizations
host# make -j30 alt install
~~~

**Comment by aivanova5** [comment]
Base image was upgraded to Python 3.9 and I no longer see this issue coming up - closing
